### ISSUE TITLE
Tablesort error on load

### ISSUE THREAD

**Issue by tablatronix** [n00dles/DM_Matrix#1]
jquery.tablesorter.js:332
Uncaught TypeError: Cannot read property 'length' of undefined

Cannot add table, due to this fatal error.

**Comment by n00dles** [comment]
As there was no row to sort on a newsly installed system (hidden tables don't count) there was nothing to sort in the table.

**Comment by tablatronix** [comment]
Oh i know, do you want me to create issues for stuff I find, or just fix stuff as I find it and do a pull request ?
This is shawn_a BTW

**Comment by n00dles** [comment]
Hey Shawn, either works for me.. if you've got the time to work on some of the issues that would be great... 
will hopefully do a good bit with it over the weekend.....

**Comment by tablatronix** [comment]
I have a fork and will commit everything I have done so far.
I would say its beta ready, but i havent tested all the datatypes yet or the internal functions.
Do you have a unit test you can put somewhere ?

**Comment by tablatronix** [comment]
Pull request done, but your last changes are not in.

**Comment by tablatronix** [comment]
Merged all changes into my fork and added to pull request
