### ISSUE TITLE
Display selected Image on select

### ISSUE THREAD

**Issue by n00dles** [n00dles/DM_Matrix#10]
When you select an image using an image field I want the returned image to be displayed in thumbnail format the fields '#image-name' div. 

Not sure how to do this though, I've tried a JS onchange on the field input but it doesn't seem to trigger on the close of the 
file picker dialog. 

Anyone any ideas how to achieve this ??

**Comment by tablatronix** [comment]
I'll take a look at it later I just did something similar. There was a gotcha I can't recall right now

**Comment by tablatronix** [comment]
Ok so onchange doesn't work for .val changes. So you have to call change() on the field yourself, if there is a way to hook the file selection and then do a field.change() if the value changed.

The other option is to replace the val function with your own, assuming its using .val to change it.

The other option is to get the filebrowser fixed so it calls a focus first then val changes WILL call change() as per jquery docs.
untested.

**Comment by tablatronix** [comment]
oh and when you click browse I noticed it goes to anchor # and jumps to the top of the page.
dont use #
use javascript:void(0) for href links.
or
always return false;

**Comment by tablatronix** [comment]
ooh you can try calling focus on the input field yourself when you click the browse button. Then the .val change to the focuses input should trigger a change() call

**Comment by tablatronix** [comment]
I tried looking at this yesterday, didnt really understand how the popup got its values back. Does that core checkin you did actually work ? Focus before value causes a change()

**Comment by n00dles** [comment]
I've added a new option to the latest 3.1.1 version of GS. 

Allows you to add callback function once a file is selected. Just add 'func=functionName' to the URL 

Now I just have to decide what size and format for the thumbnails.

**Comment by n00dles** [comment]
you need to have the latest version of filebrower.php from the SVN (updated tonight) for this to work properly, 
if your on an older version the images won't show. which is exactly what we have at the moment.

**Comment by n00dles** [comment]
I need to change the JS to view the thumbnail rather than the returned image...

**Comment by tablatronix** [comment]
I've done something like this with the item manager plugin, did you get it figured out?

**Comment by tablatronix** [comment]
Ive seen a watcher that might watch, or is there any way we can catch the return from file browser. I don't really get how it gets back to you from file browser.

**Comment by n00dles** [comment]
In filebrowser.php the JS at the start returns the selected file to the input field with the id of 'returnid' 

The new version of filebrowser has a new option to allow a callback function, which I use to get that value and then append the image below the field. 

I need to fix it to find the thumbnail version of the image and display that instead...

**Comment by tablatronix** [comment]
Yeah I was just wondering how the ckeditor window.opener thingy passes stuff back to the script, and seeing if its interceptable or detectable.
