### ISSUE TITLE
editor field doesnt work

### ISSUE THREAD

**Issue by tablatronix** [n00dles/DM_Matrix#12]
Your method of including ckeditor options as variable assignments.

Inserting the GSEDITOROPTIONS is not compatible with this object structure.
as it is an object.

This is from my gsconfig.

define('GSEDITOROPTIONS',
"enterMode: CKEDITOR.ENTER_BR,
shiftEnterMode : CKEDITOR.ENTER_P,
scayt_autoStartup:true,
customConfig : '../../../../theme/bboyApp/assets/js/cke_custom.js'
");

which causes the editor to throw this error.

Uncaught SyntaxError: Unexpected token : 

So this need to be converted to the same syntax i think, not very familiar with the ckeditor code.

Why do we have to insert our own ckeditor when the core already has one. Is there not a way to use it as is ?
Is this something i can get added to core eventually, or is everyone ( plugin authors ) reinventing the wheel or having to modify sepcifics like paths ?

**Comment by n00dles** [comment]
Yeah the CKeditor code from the core is for a single instance of CKEditor. My code allows mutliples , i'll do a quick search / replace and convert. 

Thanks for spotting... 

There is no easy way to to insert CKeditor at the moment as its tied to an ID, although doing it my way instead and tying it to a class allow plugin writers to use the core code. So any textareas with a class of 'ckeditor' will be converted.

I'll put it in the SVN for the next release...

**Comment by n00dles** [comment]
Ok a little bit more work than I thought. 

You being the regex expert !!! 8) 

any easy way to convery this 

```
enterMode: CKEDITOR.ENTER_BR,
shiftEnterMode : CKEDITOR.ENTER_P,
scayt_autoStartup:true,
customConfig : '../../../../theme/bboyApp/assets/js/cke_custom.js'
```

to this

```
CKEDITOR.config.enterMode = CKEDITOR.ENTER_BR,
CKEDITOR.config.shiftEnterMode = CKEDITOR.ENTER_P,
CKEDITOR.config.scayt_autoStartup = true,
CKEDITOR.config.customConfig = '../../../../theme/bboyApp/assets/js/cke_custom.js'
```

each option must begin with 

CKEDITOR.config. 

and ':' changed to '='

**Comment by tablatronix** [comment]
I've been messing with this stupid thing all day trying to figure out how to use replaceAll but pass configs as an object.
bout to give up.

**Comment by tablatronix** [comment]
Its alot easier than that, I just figured it out. Give me a second to figure out why its complainging bout instances and ill post it.

**Comment by tablatronix** [comment]
ok how are you assigning it to multiple instances? I don't see it. hmm how do you do code searches on here, you think it would be obvious ?

**Comment by n00dles** [comment]
CKeditor does it by default to all instances with a class of 'ckeditor' 
Haven't been able to find another way to do it.

**Comment by tablatronix** [comment]
I just checked in and pull requested it
I added code comments so you know what I did.

!IMPORTANT
This now uses a class of DMckeditor on textareas instead so we have better control over ckeditor instances with our own replaceAll function.
So it might have to be fixed on other locations in the code if you know of any.

**Comment by tablatronix** [comment]
I've tested this with multiple textedits ( maybe e should change those to "wysiwyg" datatypes ? ), ive tested with custom toolbars, and custom GSEDITOROPTIONS. works great.

Also it might be wise to make these fields not table displayable, or instead show a character count or something ?

**Comment by n00dles** [comment]
great work. No need to change class anywhere else. 

I'll change the field type to wysiwyg. 

Will be removing some field type from displaying on the table.

**Comment by tablatronix** [comment]
Oh and do you know why the ckeditor doesn't look the same as the normal one, it is missing some of the theming, like borders and background stuff.

**Comment by n00dles** [comment]
this should be sorted, it looks fine on my build.

**Comment by tablatronix** [comment]
Hmm strange , I have no gray or borders just white.

**Comment by tablatronix** [comment]
What skin are you using ?
