### ISSUE TITLE
records not saving

### ISSUE THREAD

**Issue by tablatronix** [n00dles/DM_Matrix#21]
hmm i cant get my records to save, and no errors.
Editing or adding, nothing happens.

**Comment by tablatronix** [comment]
ohh your using a 302 redirect, hmm maybe I am just not seeing the errors. Is the redirect necessary ? Can it not just be posted to the view page instead.

**Comment by n00dles** [comment]
That should be sorted now. I added a line to reread the schema when testing the routes yesterday which wasn't needed.

**Comment by tablatronix** [comment]
hmm stil no luck

**Comment by tablatronix** [comment]
Its my field names, Ill fix it

**Comment by tablatronix** [comment]
Ok so I dont know how you want to go about this.
POST variable names do not allow certain characters for obvious reasons.
space, dots, brackets etc.
so they are all converted to _ in the post variables keys.

matrix allows fieldnames to contain these characters and we are not doing any encoding or decoding of them when using them in forms.

So my field "1 test"
comes in as _POST["1_test"]

The obvious solution is str replace for a few characters for now.

But you have to consider what will happen to international fieldnames etc.
I think we should avoid using fieldnames all together and use field indexes instead.

so `<input name='fieldname with any chars in it">`
It is alot safer to use `<input name='field1''>`
on all forms.
Same goes for any table names or anything we might be using in forms.

**Comment by tablatronix** [comment]
oh fyi i just learned this, you can use arrays in forms and php automatically converts them.
`<input name='tablename[]'>`

http://php.net/manual/en/faq.html.php

**Comment by tablatronix** [comment]
also fieldnames with _ or - in them mess with the xml

Fatal error: Call to a member function children() on a non-object in /hsphere/local/home/salverso/tablatronix.com/getsimple_dev/plugins/DM_Matrix/include/DM_matrix_functions.php on line 303

PHP WARNING 134.68 ms 2.52 mb
simplexml_load_string(): Entity: line 2: parser error : StartTag: invalid element name in [/getsimple_dev/plugins/DM_Matrix/include/DM_matrix_functions.php:299]
Backtrace →
#0 getSchemaTable() called at [/getsimple_dev/plugins/DM_Matrix.php:605]
#1 matrix_manager() called at [:]
#2 call_user_func_array(,1) called at [/getsimple_dev/admin/load.php:38]

**Comment by n00dles** [comment]
originally i was only going to allow any combination of ASCII letters [a-z], numbers [0-9], or underscores (no dashes or spaces) as it says in the field name input, i just haven't coded it yet. 

Field names beginning with '_' were intended to be used for hidden tables, like for routes, settings etc... or for plugin writers that wanted to add a table that wasn't directly editable by the end user. 

So i think we can cover ourselves by restricting the table names to that. International charachters can be used elsewhere but not in field names. 

Might do a similar JS function to makeSlug that just allows the above charachters in the field name input. what do you think?

**Comment by n00dles** [comment]
I'll follow PHP variable rules and use this regex for the field names

 '[a-zA-Z_\x7f-\xff][a-zA-Z0-9_\x7f-\xff]*'

**Comment by tablatronix** [comment]
Do you know why simplxml throws a fit if fields have - or _ in them? some encode before save xml issue ?

**Comment by n00dles** [comment]
I can't duplicate this problem. 

I have tried field names with both and they are working fine.

**Comment by tablatronix** [comment]
Hmm I'll do a smaller test I'm using a unit test, see of I can narrow
it down to a specific type perhaps.

Sent from my phone

On May 24, 2012, at 4:05 PM, Mike Swan
reply@reply.github.com
wrote:

**Comment by tablatronix** [comment]
ok this one is related to fields beginning with a number.

So its obvious fieldname charsets need to be locked down to at least php userland and any simple xml limitation as well.
