### ISSUE TITLE
How is the page slug field designed ?

### ISSUE THREAD

**Issue by tablatronix** [n00dles/DM_Matrix#3]
Can the page slug field be a dropdown field pre-populated with all titles/slugs available?

**Comment by n00dles** [comment]
There is already a dropdown for that called 'pages' 

The way I'm using the page/slug dropdown at the moment is in a blog type configuration, it in conjunction with the _routes 
table. Thats not implemented fully yet so I have a small function to do it at the moment. you can see around line 122 of DM_matrix.php I have a line 

addRoute('blogger','news');

I then hook in the 'error'404' hook to call doRoute() which redirects to a 'real' page. 

This redirects any request for http://yoursite.com/blogger/whatever-your-slug-is 
-> http://yoursite.com/news 

Your news page can then take the URI, parse it, and fetch the data from the tables. 

by hooking into the 'error-404' hook and redirecting to your page. The route must be different to and existing page as the hook won't be fired. 

I wanted to do it this way so I don't have to add anything to the core or mess about with .htaccess files or redirects as I and other are not using apache and this won't work for us.. So I wanted it to work out of the box for as many systems as possible. 

What do you think ? I know its a bit of a hack but it works.... 
Any other way of doing this?

**Comment by n00dles** [comment]
You can see the 'pages' dropdown in action on the demo site. Each of the boxes has a title,info and url field. 
The url field is a pages dropdown which links to an internal GS page.

**Comment by tablatronix** [comment]
oh, I looked for pages, must have passed right over it, I see it now.

Not a fan of redirects, but i guess you would need a more logic to intercept during an earlier hook.

**Comment by n00dles** [comment]
sorry don't mean redirect, it replaces internally the filename to be read in by the system,

so url read as /blogger/your_slug
but read in file  'news' and passes the URI to the page.

**Comment by tablatronix** [comment]
ah ok, yeah that seems good enough.

Does tablesorter support inline editing ?

I use jquery datatables, it has a nice feature set and basic inline editing and i think he jsut added a new editing feature, that is more advanced but has licensing requirements.
