### ISSUE TITLE
Checkbox values

### ISSUE THREAD

**Issue by n00dles** [n00dles/DM_Matrix#30]
At the moment checkbox values are either 'on' or 'null' 
should we change this to 0 and 1 or on and off ?
which is best/more intuitive for querying?

**Comment by tablatronix** [comment]
probably boolean

**Comment by tablatronix** [comment]
Ok that was a dumb answer. Umm I'd leave it null, otherwise your stick populating default or fale values for the user

**Comment by n00dles** [comment]
ok we'll leave it as it is.

**Comment by n00dles** [comment]
I've changed it to boolean for the check boxes as it is an on/off state that were checking for.
