### ISSUE TITLE
system table - _customfields

### ISSUE THREAD

**Issue by n00dles** [n00dles/DM_Matrix#33]
Allow you to add a tables fields to a page template. 

This will replace the current customfields  plugin and allow you to have different customfields per template. 

Instead if writing data to the tables the fields will be written to the page XML files like customfields do now. 

This is easy to implement and I might do before release ? 

What do you guys think? leave it for the next release?

**Comment by tablatronix** [comment]
Thats neat, but wont you lose the ability to manage the data in matrix. Your stuck going page to page, although i guess that would let it be in pagecache it sounds like.

**Comment by n00dles** [comment]
will close this and leave customfileds alone and let the dedicated plugins do that job. 

No point in confusing things...
