### ISSUE TITLE
duplicate id in xml record

### ISSUE THREAD

**Issue by outflux3** [n00dles/DM_Matrix#38]
When i save, i am getting sometime 2 id fields, like <id>0</id><id>0</id>

**Comment by n00dles** [comment]
Ok I'm seeing this now myself, soemthing wrong with the rewrite of the save record function changed the other day...

**Comment by outflux3** [comment]
for now it doesn't seem to be adversely affecting anything, but i guess once it is fixed, i'll go in and delete the duplicate fields.... also, i have been noticing that not all of the fields are consistently saving as CDATA; not sure if they are supposed to, but most of the records in the current 2 projects i'm doing don't have CDATA within the wysiwyg field area (in the XML file)....

**Comment by n00dles** [comment]
this is sorted I'll update with the next release
