### ISSUE TITLE
wysiwyg fields getting excess backslash

### ISSUE THREAD

**Issue by outflux3** [n00dles/DM_Matrix#39]
Riptide features some of New York City\\\\'s ... 

i'm getting the backslash problem in fields that are wysiwyg; 

i'm just wondering if those wysiwyg fields are supposed to be CDATA;  i recall having this issue when first using the get simple "Items manager" plugin...

**Comment by outflux3** [comment]
also, it seems that if there is an &nbsp; within certain fields, it must be invalidating the xml file; 
i just tested this by adding an &nbsp; to a wysiwyg field on a record, and after this, the records would not show up in the listing;

**Comment by n00dles** [comment]
Think this is sorted, Added CDATA to all fields and safeslashing wysiwyg before save and removing after. 

not sure what charachter you meant above as github seems to be removing it too. 8)

**Comment by outflux3** [comment]
great!
it was an `& n b s p ;`
