### ISSUE TITLE
WSOD on record save

### ISSUE THREAD

**Issue by outflux3** [n00dles/DM_Matrix#40]
Not sure what happened, but i just installed the latest version of Matrix, and tried to add a record, but got a WSOD on this URL:

/admin/load.php?id=DM_Matrix&action=matrix_manager&add=discography&addrecord

maybe my schema is messed up;

also i was able to edit the existing records, but the wysiwyg fields didn't update to CDATA, and I am also still getting 2 ID fields in the xml file, like 

&lt;id&gt;0&lt;/id&gt;&lt;id&gt;0&lt;/id&gt;

**Comment by n00dles** [comment]
oops, typo !!

Sorry about that...

**Comment by outflux3** [comment]
hey no worries... that's what i'm here for.

**Comment by outflux3** [comment]
i guess this thread can be closed, however there still seems to be the issue of the double id field; it doesn't seem to be adversely affecting anything;
