### ISSUE TITLE
add table and sidemenu issue

### ISSUE THREAD

**Issue by tablatronix** [n00dles/DM_Matrix#49]
When i add a new table via UI get this url

http://localhost/getsimple_dev/admin/load.php?id=DM_Matrix&schema&action=matrix_manager&add

and both sidemenus for
manage table and add record are active.

Then my table is not clickable and has no edit button.

Also my old tables are all missing drop table links, is there some unlinked tracking going on that isnt picking pu my old version created tables ?

**Comment by tablatronix** [comment]
ah i see, if no fields there is no add record link or hyper link on the tablename, slightly confusing.
Should creating a table take you straight to add fields cause its not.

**Comment by n00dles** [comment]
if a table has records on the backend you can't drop it (yet) I'll have a function to nuke a table and records tonight. 

We can send them to the add fields page after creating a table, sure. But I'll leave the no link/add record options as they are in case nothing is added.

**Comment by tablatronix** [comment]
ok, The sidemenu issue is that just a missing check for a query argument in addition to the "add" one.

**Comment by n00dles** [comment]
This is fixed in the latest Rev.

**Comment by tablatronix** [comment]
I am at latest svn.

**Comment by n00dles** [comment]
it is now, windows github app had stalled...
