### ISSUE TITLE
addschema error

### ISSUE THREAD

**Issue by tablatronix** [n00dles/DM_Matrix#50]
Minor error thrown.

Warning: mkdir(): File exists in getsimple_dev/plugins/DM_Matrix/include/DM_matrix_functions.php on line 12 

I think this is trying to addAchema when it already exists.
­

**Comment by n00dles** [comment]
Fixed in the latest Rev

**Comment by tablatronix** [comment]
I am at latest svn as of this morning. Has this been pushed?
