### ISSUE TITLE
site using matrix

### ISSUE THREAD

**Issue by outflux3** [n00dles/DM_Matrix#52]
Hey - this is the 2nd site i did which makes use of Matrix:

http://www.soundingbeckett.com/

the actors & composers are all handled by the matrix; really worked out well for managing this, and easy to use for the folks who need to maintain ;

**Comment by n00dles** [comment]
Looks great !! 
Great its being used live 

I just did this one

http://www.linearoffice.com

Sorry haven't updated much in the last couple of weeks and got this released but took on too much work again and under pressure to complete.... off for a weeks holidays on sunday but will finish this off and have a full release by the end of the month....

**Comment by outflux3** [comment]
thanks Mike - nice site - looking forward to future matrix releases!
