### ISSUE TITLE
Codemirror, Syntax Highlighting

### ISSUE THREAD

**Issue by outflux3** [n00dles/DM_Matrix#9]
I haven't been able to get syntax highlighting to work on my codemirror field type; just wondering if I'm doing something wrong...that type of field would presumably have code highlighting, line number etc..(?)..is there any additional setup needed within GetSimple, or the config, for this to work?

-marc

**Comment by n00dles** [comment]
Can you try this again for me, it should be working now.

**Comment by outflux3** [comment]
Yes, it works, thanks very much!
